# Generated by Django 4.1.7 on 2023-04-01 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('desc', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=63)),
                ('state', models.CharField(max_length=63)),
                ('country', models.CharField(max_length=63)),
                ('zipcode', models.CharField(max_length=63)),
                ('phone', models.CharField(max_length=15)),
                ('img', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, verbose_name='description')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=63)),
                ('state', models.CharField(max_length=63)),
                ('country', models.CharField(max_length=63)),
                ('zipcode', models.CharField(max_length=63)),
                ('phone', models.CharField(max_length=15)),
                ('img', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, verbose_name='description')),
                ('qty', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('img', models.URLField(verbose_name='image url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.shop')),
            ],
        ),
    ]
