# Generated by Django 4.1.7 on 2023-04-22 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_cart_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 22, 2, 24, 23, 991965, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
